#ENC[AES256_GCM,data:CraVaaUzt4/25gLr7zzv8bubwplsUr6zZpQiWAf94PPRf21lm8Csld9P7wfYIpYc9tEgVvfsr/M=,iv:KX9jJGVZ5lwE0IHU7GS3nbB+x6kRr3dMU09gAAxkUAQ=,tag:5dkJ5AJXajdollHj9l8ECA==,type:comment]
#ENC[AES256_GCM,data:A1E94wqRGfEAuxy+DreY0fKTEMKuFkOdu9LDy8Rwl4VZIKw5VOtGVmAHOkXBxwA4jGU+zXJupivVpjSHcKPA1cZI5GXMeQQJHw5tLLy9NMsgKOQxPIML2Q==,iv:B7scr88Pi2Q3bsecgtQ8kGXC4E2IhG1/nTnF/2yoXeQ=,tag:dgpbYm4vXv/nmjrgLuhqMw==,type:comment]
#ENC[AES256_GCM,data:0QPN8IpWHpoBLDaJmTRCJlpuvpb+0Okjw1+C5x0dmyeW0HSnwBkwZrvVR8ywDk3JEuRF+0q2RRQmdckxdFBg5j4b1YC7BQ==,iv:GyVLk82M6HNwVlpnF57J0szkcRfX3tpq0vQZbEovFrE=,tag:DTX5TF6kYgM6iituKgL6AQ==,type:comment]
#ENC[AES256_GCM,data:Sj4bEm+aKJnLkOprBmfGAxfjtvLtDo/W5UDAkU6B4a3iXCQNyOLVCd8hgTFDuW4gdZbeXGfmyxvuU98evDI/n1D++n9Eww==,iv:0TEmK/tvK8KROWCQDFmNXoxdGsuhuk+oZvjqgN2FyjY=,tag:Q0k38zoasaeBUv/4LU1ukg==,type:comment]
vault_k3s_token: ENC[AES256_GCM,data:21gYBSjz7SzkpjnBQBMhktxJIGo163f8kFuPvxHWvJA=,iv:fh00UbnW2eAXs8TYOpDxx40XLkY78Xw/mSCv8K/F4Wc=,tag:yifa20QoSTe59/vGwSNHLQ==,type:str]
#ENC[AES256_GCM,data:poGoz5N6tfQZUgcvpM6EY9q5m+wR51hmv7hYmEYgqnvsrrjy3yc5yrYH4fsCdGmUd3/NdjTUZ3xxiisKEhxlLj3mN/RD1exW,iv:8elFJkPADW+cMKd9d0DtWIiLgb+Z7SP9gRquhqI9wtQ=,tag:TbWtDbvQ1x4dZKsLGcKcdg==,type:comment]
vault_custom_registries_auth:
    registry_domain: ENC[AES256_GCM,data:cPVKC/DLcBw/Wl5fuff+VEZ2yg==,iv:8g/0pQPx2hDNO8I2wb8ZO9nkgYJZhK48M3Z46wnc2Sc=,tag:eStiP9vq/Ca2Z48T9qwvYA==,type:str]
    username: ENC[AES256_GCM,data:oVRJBCOH+EmSx+pB,iv:lNX5Q1GeugJpspdd8rnoUVZTo6fYlJmqHBnsgMtpE3w=,tag:aB+14PZnGZn5LeoM1/THWQ==,type:str]
    password: ENC[AES256_GCM,data:BW8dYjAbH2n4JJ3O,iv:6HAhPqzfWfrtbyomsSygnBP9zCamDN8h2tlv2R/HPwE=,tag:dZoVAWE7laLHmA9UZATPWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZzZ2OUc0bmFPM1ZLYkV5
            RGpZbXAybnQvTkFkc0hIWXUxZG5DcU5vZ2pBCjJCcmV6aW1uTnNocE1SYkZ4VTZ3
            SHBQRGtBck1EM1VVdDYvSDlpMDllTmMKLS0tIDR4bzA0ek1XTjJjOXpJZncvLzRj
            cVNhZk9kQThRZVk1K3hyMXc0bkM2YlUKE1IvESR+iBkLsKRHr8hoXQ6kOHvyMsNP
            9qvPo3ndXmFGsU1qK0Z/WvHQzvbCmak2q28xVg7jkbIiThwLImLHyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tq4alh5r9fanehqva3ev9l6lrr82vzt6cxhs0ak69g3erwhrff9qe60q47
    lastmodified: "2026-09-10T23:40:28Z"
    mac: ENC[AES256_GCM,data:SW0AEhFxxQ0GtuclV/rYw3HPq+NymeWGmW9YSx6Uv0nPMUboEh+Gvp6D/GkAOuPkv6zeVxvWFvlJiixXze8PmoboTjnVP7qjtIbWWqyOxLnxxl6Y5u8QDDpkfwudgzgZ+mDV3enJNIIY+2d8Nde7r2iK+CE0UR+hufkcM8Rh8o0=,iv:Urrf7c6dfR2j4hY/k6fS98MHRcrnauDgN9tSTr6nyHY=,tag:Z4Er40vh+M0OgK+7EAXTYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
